name: Test
on:
  push: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: setup gauge
        run: |
          npm install -g @getgauge/cli
      - run: yarn
      - run: yarn test
        env:
          CI: true
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@e0c5ab92a572c0a97d95564c9bd1d7c131623ff1
        if: "github.ref == 'refs/heads/master'"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: reports/html-report
          GIT_CONFIG_NAME: dtinth-bot
          GIT_CONFIG_EMAIL: dtinth-bot@users.noreply.github.com
