name: Test
on:
  push: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: setup gauge
        run: |
          sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
          echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install gauge -y
          gauge install
      - run: yarn
      - run: yarn test
        env:
          CI: true
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@e0c5ab92a572c0a97d95564c9bd1d7c131623ff1
        if: "github.ref == 'refs/heads/master'"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: reports/html-report
          GIT_CONFIG_NAME: dtinth-bot
          GIT_CONFIG_EMAIL: dtinth-bot@users.noreply.github.com
